# Generated by Django 5.1.1 on 2024-10-06 09:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='eventTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=85)),
                ('content', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='event_description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_name',
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_view_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
