# Generated by Django 5.1.1 on 2024-10-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0002_eventtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_name', models.CharField(max_length=85)),
                ('ev_desc', models.CharField(max_length=300)),
            ],
        ),
    ]
