# Generated by Django 5.1.1 on 2024-10-11 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0003_create_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.DeleteModel(
            name='eventTitle',
        ),
        migrations.AddField(
            model_name='create_event',
            name='ev_image',
            field=models.ImageField(default='media\recipe\\9f97f71d4af84228bf7290556613ecec_8BuuHxa.jpg', upload_to='event'),
        ),
        migrations.AddField(
            model_name='create_event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
