# Generated by Django 5.1.1 on 2024-10-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0004_remove_event_user_delete_eventtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_event',
            name='ev_view_count',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='create_event',
            name='ev_image',
            field=models.ImageField(upload_to='EventManager'),
        ),
    ]
