# Generated by Django 5.1.1 on 2024-10-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0005_create_event_ev_view_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_event',
            name='ev_image',
            field=models.ImageField(blank=True, null=True, upload_to='EventManager'),
        ),
    ]
