# Generated by Django 5.1.1 on 2024-10-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0008_create_event_ev_date_alter_create_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_event',
            name='ev_location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
