# Generated by Django 5.1.1 on 2024-10-22 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0009_create_event_ev_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='create_event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='rsvps', to=settings.AUTH_USER_MODEL),
        ),
    ]
